services:
  stock-stream:
    image: confluentinc/cp-kafka:latest
    container_name: stock-stream
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://stock-stream:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - back-tier
    ports:
      - "9092:9092"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - back-tier

  stock-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: stock-api
    networks:
      - back-tier
    depends_on:
      - stock-stream
    environment:
      KAFKA_BROKER: stock-stream:9092
    ports:
      - "8000:8000"

networks:
  back-tier:
    driver: bridge